# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃       Velocitab Config       ┃
# ┃    Developed by William278   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┣╸ Information: https://william278.net/project/velocitab
# ┗╸ Documentation: https://william278.net/docs/velocitab
# Check for updates on startup
check_for_updates: true
# Header(s) to display above the TAB list for each server group.
# List multiple headers and set update_rate to the number of ticks between frames for basic animations
headers:
  default:
  - |

    <bold><#DA2117>Civ</#DA2117><#93180F>Cubed</#93180F></bold>

# Footer(s) to display below the TAB list for each server group, same as headers.
footers:
  default:
  - |

    <gray>%players_online% players are online</gray>
    Join the community online at <underlined><#2aa1bf>https://civcubed.net</#2aa1bf></underlined>

formats:
  default: '%prefix%%username%'
# Which text formatter to use (MINEDOWN, MINIMESSAGE, or LEGACY)
formatting_type: MINIMESSAGE
# The servers in each group of servers
server_groups:
  default:
  - hub
  - main
# All servers which are not in other groups will be put in the fallback group.
# "false" will exclude them from Velocitab.
fallback_enabled: true
# The formats to use for the fallback group.
fallback_group: default
# Only show other players on a server that is part of the same server group as the player.
only_list_players_in_same_group: true
# Define custom names to be shown in the TAB list for specific server names.
# If no custom display name is provided for a server, its original name will be used.
server_display_names:
  very-long-server-name: VLSN
# Whether to enable the PAPIProxyBridge hook for PAPI support
enable_papi_hook: true
# How long in seconds to cache PAPI placeholders for, in milliseconds. (0 to disable)
papi_cache_time: 30000
# If you are using MINIMESSAGE formatting, enable this to support MiniPlaceholders in formatting.
enable_miniplaceholders_hook: true
# Whether to sort players in the TAB list.
sort_players: true
# Ordered list of elements by which players should be sorted. (ROLE_WEIGHT, ROLE_NAME and SERVER are supported)
sort_players_by:
- ROLE_WEIGHT
- ROLE_NAME
# How often in milliseconds to periodically update the TAB list, including header and footer, for all users.
# If set to 0, TAB will be updated on player join/leave instead. (1s = 1000ms)
# The minimal update rate is 200ms, anything lower will automatically be set to 200ms.
update_rate: 0
