- name: Create hub server group
  group:
    name: hub-server
    state: present

- name: Create hub server user
  user:
    name: hub-server
    group: hub-server
    comment: "User for CivCubed Hub Server"
    state: present

- name: Create hub server directory
  file:
    path: /CivCubed/Hub
    owner: hub-server
    group: hub-server
    state: directory
    mode: '0755'

- name: Download Paper
  get_url:
    url: https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/43/downloads/paper-1.20.1-43.jar
    dest: /CivCubed/Hub/paper.jar
    mode: '0775'
    group: hub-server
    owner: hub-server

- name: Create hub server plugins directory
  file:
    path: /CivCubed/Hub/plugins
    owner: hub-server
    group: hub-server
    state: directory
    mode: '0755'

- name: Download BallCore Hub
  get_url:
    url: https://github.com/BlueMoonVineyard/BallCore/releases/download/ci/BallCoreHub.jar
    dest: /CivCubed/Hub/plugins/BallCoreHub.jar
    mode: '0660'
    group: hub-server
    owner: hub-server

- name: Download LuckPerms
  get_url:
    url: https://download.luckperms.net/1503/bukkit/loader/LuckPerms-Bukkit-5.4.89.jar
    dest: /CivCubed/Hub/plugins/LuckPerms.jar
    mode: '0660'
    group: hub-server
    owner: hub-server

- name: Download AdvancedPortals
  get_url:
    url: https://cdn.modrinth.com/data/axTqSWQA/versions/tj8xmw88/Advanced-Portals-0.9.2.jar
    dest: /CivCubed/Hub/plugins/AdvancedPortals.jar
    mode: '0660'
    group: hub-server
    owner: hub-server

- name: Download FAWE
  get_url:
    url: https://ci.enginehub.org/repository/download/bt10/22158:id/worldedit-bukkit-7.2.16-SNAPSHOT-dist.jar?branch=version/7.2.x&guest=1
    dest: /CivCubed/Hub/plugins/FAWE.jar
    mode: '0660'
    group: hub-server
    owner: hub-server

- name: Copy server.properties
  copy:
    src: server.properties
    dest: /CivCubed/Hub/server.properties
    mode: '0660'
    group: hub-server
    owner: hub-server

- name: Copy eula.txt
  copy:
    src: eula.txt
    dest: /CivCubed/Hub/eula.txt
    mode: '0660'
    group: hub-server
    owner: hub-server

- name: Create hub server luckperms config directory
  file:
    path: /CivCubed/Hub/plugins/LuckPerms
    owner: hub-server
    group: hub-server
    state: directory
    mode: '0755'

- name: Copy LuckPerms config.yml
  template:
    src: ../../Common/LuckPermsConfig.yml.j2
    dest: /CivCubed/Hub/plugins/LuckPerms/config.yml
    mode: '0660'
    group: hub-server
    owner: hub-server
  vars:
    server: hub

- name: Create hub server config directory
  file:
    path: /CivCubed/Hub/config
    owner: hub-server
    group: hub-server
    state: directory
    mode: '0755'

- name: Copy paper-global.yml
  template:
    src: paper-global.yml.j2
    dest: /CivCubed/Hub/config/paper-global.yml
    mode: '0660'
    group: hub-server
    owner: hub-server

- name: Copy hub server systemd unit
  copy:
    src: HubServer.service
    dest: /usr/lib/systemd/system/HubServer.service

- name: Start hub server systemd unit
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: no
    name: HubServer
