- name: Create Velocity server group
  group:
    name: velocity-server
    state: present

- name: Create Velocity server user
  user:
    name: velocity-server
    group: velocity-server
    comment: "User for CivCubed Velocity Server"
    state: present

- name: Create Velocity server directory
  file:
    path: /CivCubed/Velocity
    owner: velocity-server
    group: velocity-server
    state: directory
    mode: '0755'

- name: Create Velocity plugin directory
  file:
    path: /CivCubed/Velocity/plugins
    owner: velocity-server
    group: velocity-server
    state: directory
    mode: '0755'

- name: Download Velocity
  get_url:
    url: https://api.papermc.io/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/258/downloads/velocity-3.2.0-SNAPSHOT-258.jar
    dest: /CivCubed/Velocity/velocity.jar
    mode: '0775'
    group: velocity-server
    owner: velocity-server

- name: Copy velocity.toml
  copy:
    src: velocity.toml
    dest: /CivCubed/Velocity/velocity.toml
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Copy server icon
  copy:
    src: server-icon.png
    dest: /CivCubed/Velocity/server-icon.png
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Download LuckPerms
  get_url:
    url: https://download.luckperms.net/1519/velocity/LuckPerms-Velocity-5.4.106.jar
    dest: /CivCubed/Velocity/plugins/LuckPerms.jar
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Download AdvancedPortals
  get_url:
    url: https://cdn.modrinth.com/data/axTqSWQA/versions/tj8xmw88/Advanced-Portals-0.9.2.jar
    dest: /CivCubed/Velocity/plugins/AdvancedPortals.jar
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Download Velocitab
  get_url:
    url: https://hangarcdn.papermc.io/plugins/William278/Velocitab/versions/1.4.1/VELOCITY/Velocitab-1.4.1.jar
    dest: /CivCubed/Velocity/plugins/Velocitab.jar
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Create Velocity server luckperms config directory
  file:
    path: /CivCubed/Velocity/plugins/LuckPerms
    owner: velocity-server
    group: velocity-server
    state: directory
    mode: '0755'

- name: Copy LuckPerms config.yml
  template:
    src: ../../Common/LuckPermsConfig.yml.j2
    dest: /CivCubed/Velocity/plugins/LuckPerms/config.yml
    mode: '0660'
    group: velocity-server
    owner: velocity-server
  vars:
    server: velocity

- name: Create Velocity server velocitab config directory
  file:
    path: /CivCubed/Velocity/plugins/velocitab
    owner: velocity-server
    group: velocity-server
    state: directory
    mode: '0755'

- name: Copy Velocitab config.yml
  copy:
    src: velocitab.yml
    dest: /CivCubed/Velocity/plugins/velocitab/config.yml
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Copy ForcePack
  copy:
    src: ForcePack-1.2.9.jar
    dest: /CivCubed/Velocity/plugins/ForcePack.jar
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Create Velocity server forcepack config directory
  file:
    path: /CivCubed/Velocity/plugins/forcepack
    owner: velocity-server
    group: velocity-server
    state: directory
    mode: '0755'

- name: Create Velocity server ballcorevelocityplugin config directory
  file:
    path: /CivCubed/Velocity/plugins/ballcorevelocityplugin
    owner: velocity-server
    group: velocity-server
    state: directory
    mode: '0755'

- name: Copy BallCore velocity plugin config
  template:
    src: CivCubedConfig.yaml.j2
    dest: /CivCubed/Velocity/plugins/ballcorevelocityplugin/config.yaml
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Copy ForcePack config.toml
  copy:
    src: forcepack.toml
    dest: /CivCubed/Velocity/plugins/forcepack/config.toml
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Symlink BallCore CommonCode
  file:
    src: /CivCubed/BallCoreCommonCode.jar
    dest: /CivCubed/Velocity/plugins/BallCoreCommonCode.jar
    owner: velocity-server
    group: velocity-server
    state: link

- name: Symlink BallCore Dependency Plugin
  file:
    src: /CivCubed/BallCoreDependencyPlugin.jar
    dest: /CivCubed/Velocity/plugins/BallCoreDependencyPlugin.jar
    owner: velocity-server
    group: velocity-server
    state: link

- name: Download BallCore VelocityPlugin
  get_url:
    url: https://github.com/BlueMoonVineyard/BallCore/releases/download/ci/BallCoreVelocityPlugin.jar
    dest: /CivCubed/Velocity/plugins/BallCoreVelocityPlugin.jar
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Copy forwarding secret
  template:
    src: forwarding.secret.j2
    dest: /CivCubed/Velocity/forwarding.secret
    mode: '0660'
    group: velocity-server
    owner: velocity-server

- name: Copy Velocity server systemd unit
  copy:
    src: VelocityServer.service
    dest: /usr/lib/systemd/system/VelocityServer.service

- name: Start Velocity server systemd unit
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: no
    name: VelocityServer
