---
- hosts: all
  vars_files: ../vault.yml
  roles:
  - role: Common

- hosts: main_server
  vars_files: ../vault.yml
  roles:
  - role: MainServer

- hosts: database
  vars_files: ../vault.yml
  roles:
  - role: Database

- hosts: hub_server
  vars_files: ../vault.yml
  roles:
  - role: HubServer

- hosts: velocity_server
  vars_files: ../vault.yml
  roles:
  - role: VelocityServer

- hosts: flarum
  vars_files: ../vault.yml
  roles:
  - role: Flarum
